### ISSUE TITLE
Enable dynamic linking to third party services for each dataset

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#602]
Much like a typical desktop operating system allows you to choose which application you use to open a certain kind of file, we should enable users to choose which third party service to use to open a dataset on data.gov without needing to download/upload to that service.

**Comment by philipashlock** [comment]
Ideally this would compliment the built-in "Preview" functionality and would work in a somewhat similar way. Currently the "Preview" button only appears after we verify that the file linked to is previewable. We'll need to do this for third party services as well and so we might as well display the "Preview" option in the same way as third party services. 

Here's what the UI could look like:

![screen shot 2015-03-02 at 4 52 32 pm](https://cloud.githubusercontent.com/assets/183402/6451509/db78b05c-c0fc-11e4-953d-2d7d3dd526f0.png)

Ideally each provider would simply be a configuration option. Here's what configuration might look like in YAML:

```
external_file_readers: 
  - 
    name: "Map Provider"
    url_scheme: "https://www.map-provider.demo/external/?url="
    media_type: 
      - application/vnd.ms-excel
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - text/csv
      - application/vnd.google-earth.kml+xml
      - application/vnd.geo+json
  - 
    name: "Data Viz Provider"
    url_scheme: "https://www.dataviz-provider.demo/external/?url="
    media_type: 
      - application/vnd.ms-excel
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - text/csv
      - text/tab-separated-values
```
